// GENERATED by mesh_bridge/kcdlib/ptf.py --emit-cpp= -- DO NOT EDIT BY HAND.
//
// The PTF merge table: for each file family, which element path carries rows, what makes
// two rows THE SAME row, where a new row sorts, and which number a second mod would
// collide on. Every rule here is checked against a shipped artifact by `ptf_verify.py`:
// merge(vanilla, diff(vanilla, override)) must reproduce that override byte for byte.
//
// Regenerate with:  python mesh_bridge/kcdlib/ptf.py --emit-cpp=<this file>

#pragma once

#include <cstddef>

namespace ptf {

struct FamilyRule {
    const char* path;      // element path whose children are rows
    const char* identity;  // attr:X[+attr:Y][+child:Z] -- what makes two rows the same
    const char* order;     // append | sorted:attr:X[|suffix_] | sorted:child:X | clone
    const char* allocate;  // attr:X / child:X, or nullptr -- a number two mods would pick
    const char* conflict;  // last-wins | error | chain
};

struct Family {
    const char*       name;
    const char*       glob;    // levels/*/leveldata.xml -- `*` never crosses a separator
    const char*       expect;
    const FamilyRule* rules;
    std::size_t       ruleCount;
};

inline const FamilyRule kLeveldataRules[] = {
    {"/LevelData/Layers/Layer",
     "attr:Name",
     "sorted:attr:Name|suffix_", "attr:Id", "last-wins"},
};

inline const FamilyRule kWhdataRules[] = {
    {"/Root/GameProfileManager/GameProfiles/GameProfile",
     "child:Name",
     "sorted:child:Name", "child:Id", "last-wins"},
};

inline const FamilyRule kObjectsMissionRules[] = {
    {"/Objects/Entity",
     "attr:EntityGuid",
     "sorted:attr:EntityGuid", "attr:EntityId", "last-wins"},
};

inline const FamilyRule kWaitinglinksRules[] = {
    {"/StaticLinksInfo/WaitingLinks/WaitingLink",
     "attr:SourceId+attr:TargetId+child:LinkDefinition",
     "append", nullptr, "last-wins"},
};

inline const FamilyRule kUiTableRules[] = {
    {"/database/Cutscenes/*",
     "attr:Name",
     "append", nullptr, "last-wins"},
};

inline const FamilyRule kSkaldRules[] = {
    {"**/Edge",
     "attr:From+attr:To",
     "append", nullptr, "chain"},
    {"/Database/Skald/*/EdgeVertices/EdgeVertex",
     "attr:Name",
     "append", nullptr, "last-wins"},
    {"/Database/Skald/*/Nodes/*",
     "attr:Name",
     "append", nullptr, "last-wins"},
    {"/Database/Skald/*/Ports/Port",
     "attr:Name",
     "append", nullptr, "last-wins"},
};

inline const Family kFamilies[] = {
    {"leveldata", "levels/*/leveldata.xml", "byte",
     kLeveldataRules, sizeof(kLeveldataRules) / sizeof(kLeveldataRules[0])},
    {"whdata", "levels/*/whdata_1", "eol",
     kWhdataRules, sizeof(kWhdataRules) / sizeof(kWhdataRules[0])},
    {"objects_mission", "levels/*/objects_mission0.xml", "byte",
     kObjectsMissionRules, sizeof(kObjectsMissionRules) / sizeof(kObjectsMissionRules[0])},
    {"waitinglinks", "levels/*/waitinglinks.xml", "rowset",
     kWaitinglinksRules, sizeof(kWaitinglinksRules) / sizeof(kWaitinglinksRules[0])},
    {"ui_table", "libs/tables/*/*.xml", "rowset",
     kUiTableRules, sizeof(kUiTableRules) / sizeof(kUiTableRules[0])},
    {"skald", "quests/*", "report",
     kSkaldRules, sizeof(kSkaldRules) / sizeof(kSkaldRules[0])},
};
inline const std::size_t kFamilyCount = sizeof(kFamilies) / sizeof(kFamilies[0]);

}  // namespace ptf
