-- generated by generate_skald_lua.py; do not edit by hand
-- Public helper namespace and native bridge validation.
local raw_skald = SKALD
if type(raw_skald) ~= "table" then
    error("[LuaUtils] skald/init.lua: native SKALD table missing")
end
local Public = rawget(_G, "Skald")
if Public == nil then
    Public = {}
    _G.Skald = Public
elseif type(Public) ~= "table" then
    error("[LuaUtils] global Skald already exists and is not a table")
end
return Public
