#pragma once
// libKCD2 umbrella (mirrors libKCD1's analysis/gen_kcd.py output).
// Force-included via the PCH so every RE'd header sees the real SDK types AND the rest of
// the RE surface, exactly like libKCD1. Order: std -> CryEngine SDK types -> Offsets ->
// RE'd vtable bases -> concrete classes.

// ---- std ----
#include <cstdint>
#include <cstring>
#include <cstdio>
#include <cassert>
#include <cstddef>
#include <vector>
#include <unordered_set>
#include <unordered_map>
#include <map>
#include <set>
#include <functional>
#include <string>

// ---- CryEngine SDK types (stock; the real Vec3/Quat/Matrix34/CryStringT/DynArray) ----
#include "CryEngine/CryCommon/BaseTypes.h"
#include "CryEngine/CryCommon/CryString.h"   // CryStringT<char>
#include "CryEngine/CryCommon/Cry_Math.h"    // Vec3 / Vec2 / Quat / QuatT / Matrix34 (self-includes platform.h)
#include "CryEngine/CryCommon/Cry_Geo.h"     // AABB (self-includes Cry_Math.h)
#include "CryEngine/CryCommon/CryArray.h"    // DynArray

// ---- Offsets / RTTI infrastructure (must precede class headers) ----
#include "Offsets/Offsets.h"
#include "Offsets/Offsets_VTABLE.h"
#include "Offsets/Offsets_RTTI.h"
#include "Offsets/RTTI.h"

// ---- RE'd vtable bases (KCD2 binary slot orders) ----
#include "Offsets/vtables/IScriptTable.h"
#include "Offsets/vtables/IScriptSystem.h"
#include "Offsets/vtables/IConsole.h"
#include "Offsets/vtables/ILog.h"
#include "Offsets/vtables/ISystem.h"
#include "Offsets/vtables/IEntity.h"
#include "Offsets/vtables/IGameFramework.h"
#include "Offsets/vtables/IActor.h"
#include "Offsets/vtables/IGame.h"
#include "Offsets/vtables/IGameStartup.h"
#include "Offsets/vtables/ITimer.h"
#include "Offsets/vtables/IViewSystem.h"
#include "Offsets/vtables/IEntitySystem.h"
#include "Offsets/vtables/IInput.h"
#include "Offsets/vtables/IInputEventListener.h"
#include "Offsets/vtables/IActionMapManager.h"
#include "Offsets/vtables/IGameFrameworkListener.h"
#include "Offsets/vtables/I3DEngine.h"
#include "Offsets/vtables/IRenderer.h"
#include "Offsets/vtables/IFlashPlayer.h"
#include "Offsets/vtables/IFlashPlayer_RenderProxy.h"
#include "Offsets/vtables/IFlashVariableObject.h"
#include "Offsets/vtables/IFlashUI.h"
#include "Offsets/vtables/IUIElement.h"
#include "Offsets/vtables/IFSCommandHandler.h"
#include "Offsets/vtables/IExternalInterfaceHandler.h"
#include "Offsets/vtables/IVirtualKeyboardEvents.h"
#include "CryEngine/CryCommon/CFlashUIElement.h"
#include "Scaleform/GRefCountImplCore.h"
#include "Scaleform/GFxStateBag.h"
#include "Scaleform/GASString.h"
#include "Scaleform/GFxLoadQueueEntry.h"
#include "Scaleform/GFxMovieView.h"
#include "Scaleform/GFxMovieRoot.h"
#include "CryEngine/CryCommon/CFlashPlayer.h"
#include "Offsets/vtables/IUIEventSystem.h"
#include "Offsets/vtables/IUIElementEventListener.h"
#include "Offsets/vtables/IUIAction.h"
#include "Offsets/vtables/IServiceListener.h"
#include "Offsets/vtables/IActionListener.h"

// ---- RE'd concrete engine classes (real members; use SDK/std types). These are OUR
//      reverse-engineered definitions, kept in crysystem/ (NOT the stock CryCommon SDK folder). ----
#include "crysystem/CScriptTable.h"
#include "crysystem/CScriptSystem.h"
#include "crysystem/CXConsole.h"
#include "crysystem/CSystem.h"
#include "crysystem/CEntity.h"
#include "crysystem/CEntitySystem.h"
#include "crysystem/IEntitySystemSink.h"
#include "crysystem/CCryAction.h"
#include "entitymodule/C_Actor.h"
#include "game/C_Game.h"
#include "game/C_GameStartup.h"

// ---- Round 1: engine/globals foundation (gEnv, camera, movie, rpg params, game context) ----
#include "crysystem/SSystemGlobalEnvironment.h"   // gEnv
#include "crysystem/SCameraParams.h"
#include "crysystem/CMovieSystem.h"
#include "rpgmodule/S_RpgParams.h"
#include "game/S_GameContext.h"
#include "playermodule/C_PlayerModule.h"
#include "combatmodule/C_CombatActor.h"

// ---- Tranche 1: foundation (actor hierarchy + signal + module message) ----
#include "framework/C_Signal.h"
#include "framework/S_WuidSlot.h"       // generation-counted registry slot (0x10)
#include "framework/HashPrimitives.h"   // FNV-1a/FNV-1 + S_DefaultHash for std:: unordered keys
#include "framework/InplaceVector.h"    // std::vector with inline small-buffer storage
#include "framework/C_Listeners.h"      // C_Listeners<L,N> / C_DependentListeners<L,K,N> registries
#include "framework/C_ModuleMessage.h"
#include "framework/CryDeferrable.h"
#include "entitymodule/I_ItemAttachmentListener.h"
#include "entitymodule/I_EquipmentManagerListener.h"
#include "entitymodule/C_Actor.h"
#include "entitymodule/C_Human.h"
#include "entitymodule/C_Animal.h"
#include "entitymodule/C_Horse.h"
#include "entitymodule/C_Player.h"

// ---- Tranche 2: item / inventory ----
#include "entitymodule/C_Item.h"
#include "entitymodule/C_Inventory.h"
#include "entitymodule/C_WorldInventory.h"
#include "entitymodule/C_EquipmentManager.h"
#include "entitymodule/C_InventoryManager.h"
#include "entitymodule/C_ItemManager.h"

// ---- Tranche 3: combat subsystems (model-property family + per-actor combat state) ----
#include "framework/ModelPropertyTraits.h"
#include "combatmodule/CombatModelTraits.h"
#include "framework/C_ModelProperty.h"
#include "framework/C_ModelRefProperty.h"
#include "framework/C_ModelContextProperty.h"
#include "framework/C_ModelSetProperty.h"
#include "framework/C_ModelArrayProperty.h"
#include "combatmodule/S_CombatActorState.h"
#include "combatmodule/C_CombatActorObject.h"
#include "combatmodule/C_CombatActorUpdatedObject.h"
#include "combatmodule/S_CombatCollisionDetails.h"
#include "combatmodule/S_CombatAnimCollision.h"
#include "combatmodule/C_WeaponProcSolver.h"
#include "combatmodule/C_WeaponSolver.h"
#include "combatmodule/C_CombatActorCollisions.h"
#include "combatmodule/C_CombatActorAnimCollisions.h"
#include "combatmodule/I_CombatComboManager.h"
#include "combatmodule/C_CombatComboManager.h"
#include "combatmodule/C_CombatActorOpponentManager.h"
#include "combatmodule/I_CombatActorHuntAttack.h"
#include "combatmodule/C_CombatActorHuntAttack.h"
#include "combatmodule/C_CombatActorActionManager.h"
#include "framework/C_ActionDirector.h"
#include "combatmodule/C_CombatActorDirector.h"
#include "combatmodule/C_CombatAutomationAction.h"
#include "combatmodule/C_CombatAutomationDirector.h"
#include "combatmodule/C_CombatAutomationBattlement.h"
#include "combatmodule/C_CombatAutomationAttack.h"
#include "combatmodule/C_CombatAutomationCombo.h"
#include "combatmodule/C_CombatAutomationMissile.h"
#include "combatmodule/C_CombatAutomationZoneChange.h"
#include "combatmodule/C_CombatAutomationGuard.h"
#include "game/I_EntitySideEffectCallback.h"
#include "combatmodule/C_CombatAutomationWeapons.h"
#include "combatmodule/S_CombatAutomationModels.h"
#include "combatmodule/C_CombatAutomationDefense.h"
#include "combatmodule/C_CombatAutomationRiposte.h"
#include "combatmodule/C_CombatTemporaryAutomationGuardStarter.h"
#include "combatmodule/I_CombatAutomation.h"
#include "combatmodule/C_CombatAutomation.h"

// ---- Tranche 4: C_Actor / C_Player embedded sub-structs ----
#include "entitymodule/C_AuxLightAttachment.h"
#include "entitymodule/C_PlayerMaterialEffects.h"
#include "entitymodule/C_MissileWeaponPlayerController.h"
#include "framework/CStateMachine.h"
#include "entitymodule/C_PhysicsIgnoreLists.h"
#include "entitymodule/C_BoneSlotSystem.h"
#include "animationmodule/C_LookAimIK.h"
#include "entitymodule/C_IdleState.h"
#include "entitymodule/C_StanceState.h"
#include "entitymodule/C_ActorMoveParams.h"
#include "entitymodule/C_ActorBounds.h"
#include "entitymodule/S_MountAnimState.h"

// ---- Tranche 5: RPG core (souls / buffs / factions / module) ----
#include "framework/C_ParallelModuleUpdater.h"
#include "framework/I_ScheduleUpdatable.h"
#include "databasemodule/I_DatabaseListener.h"
// soul stack
#include "rpgmodule/I_Soul.h"
#include "rpgmodule/I_InventorySoul.h"
#include "rpgmodule/I_SoulResolver.h"
#include "rpgmodule/S_ModifierNode.h"
#include "rpgmodule/C_SoulPropertyNotifier.h"
#include "rpgmodule/C_CombatSoul.h"
#include "rpgmodule/C_InventorySoul.h"
#include "rpgmodule/C_CompanionManager.h"
#include "rpgmodule/C_PerkList.h"
#include "rpgmodule/S_SoulStatBlock.h"
#include "rpgmodule/C_SoulRPGStats.h"
#include "rpgmodule/S_SoulRegistry.h"
#include "rpgmodule/C_SoulBuffList.h"
#include "rpgmodule/C_Soul.h"
#include "rpgmodule/C_StormProgram.h"
#include "rpgmodule/C_SoulList.h"
// buff stack
#include "rpgmodule/I_BuffManager.h"
#include "rpgmodule/C_BuffInstanceBase.h"
#include "rpgmodule/C_BuffInstance.h"
#include "rpgmodule/C_SoulBuffInstance.h"
#include "rpgmodule/C_TimedSoulBuffInstance.h"
#include "rpgmodule/C_BuffManager.h"
// faction stack
#include "rpgmodule/I_FactionManager.h"
#include "rpgmodule/S_FactionDefinitionID.h"
#include "framework/S_BoostOptional.h"
#include "rpgmodule/S_LocationId.h"
#include "rpgmodule/S_FactionNeighbor.h"
#include "rpgmodule/C_FactionAngriness.h"
#include "rpgmodule/C_FactionRelation.h"
#include "rpgmodule/C_FactionBase.h"
#include "rpgmodule/C_Faction.h"
#include "rpgmodule/C_FactionManager.h"
// module
#include "rpgmodule/S_RPGCVars.h"
#include "rpgmodule/C_RPGModule.h"

// ---- Tranche 6: Lua ScriptBind surface + item runtime data + RPG value enums ----
  // enums (index the S_SoulStatBlock arrays / GetDerivedStat string codes)
  #include "rpgmodule/E_SoulStat.h"
  #include "rpgmodule/E_SoulSkill.h"
  #include "rpgmodule/E_DerivedStat.h"
#include "rpgmodule/E_SoulCondition.h"
// ScriptBind surface (the Lua cheat entry points; fn tables documented per header)
#include "crysystem/CScriptableBase.h"
#include "rpgmodule/C_ScriptBindSoul.h"
#include "rpgmodule/C_FactionScriptBind.h"
#include "rpgmodule/C_LocationScriptBind.h"
#include "rpgmodule/C_ScriptBindRPGModule.h"
#include "entitymodule/C_ScriptBindActor.h"
#include "entitymodule/C_ScriptBindPlayer.h"
#include "entitymodule/C_ScriptBindHorse.h"
#include "entitymodule/C_ScriptBindHuman.h"
#include "entitymodule/C_ScriptBindInventory.h"
#include "entitymodule/C_ScriptBindItemManager.h"
#include "shopmodule/C_ScriptBindShop.h"
// item runtime-data family (C_Item+0x58 pointee hierarchy)
#include "entitymodule/I_ItemRuntimeData.h"
#include "entitymodule/C_ConsumableRuntimeData.h"
#include "entitymodule/C_KeyRuntimeData.h"
#include "entitymodule/C_EquippableItemRuntimeData.h"
#include "entitymodule/C_ArmorRuntimeData.h"
#include "entitymodule/C_WeaponEquipRuntimeData.h"
#include "entitymodule/C_AmmoRuntimeData.h"
#include "entitymodule/C_WeaponRuntimeData.h"
#include "entitymodule/C_MeleeWeaponRuntimeData.h"
#include "entitymodule/C_MissileWeaponRuntimeData.h"

// ---- Tranche 7: buff instance leaves + buff init-params + save-game stack ----
// buff leaves (below the C_SoulBuffInstance / C_TimedSoulBuffInstance anchors)
#include "rpgmodule/C_ConstantSoulBuffInstance.h"
#include "rpgmodule/C_ConstantContextCheckingSoulBuffInstance.h"
#include "rpgmodule/C_CombatContextSoulBuffInstance.h"
#include "rpgmodule/C_InstantSoulBuffInstance.h"
#include "rpgmodule/C_TwoStateSoulBuffInstance.h"
#include "rpgmodule/C_TwoStateWithActivationSoulBuffInstance.h"
#include "rpgmodule/C_WantedBuff.h"
#include "rpgmodule/C_ModifiableTimedBuff.h"
#include "rpgmodule/C_WorldTimeTimedBuff.h"
#include "rpgmodule/C_BleedingBuffInstance.h"
// buff init-params family
#include "rpgmodule/I_BuffInitParams.h"
#include "rpgmodule/C_BuffInitParamsDefault.h"
#include "rpgmodule/C_ItemBuffInitParams.h"
// save-game stack (framework; owner C_PlayerProfileWHManager not yet RE'd)
#include "framework/E_SaveGameType.h"
#include "framework/I_ReadinessDebuggable.h"
#include "framework/I_ReadinessTask.h"
#include "framework/C_ReadinessObserver.h"
#include "framework/C_CrySaveGameHelper.h"
#include "framework/C_CryLoadGameHelper.h"
#include "framework/C_SaveGameDescription.h"
#include "framework/S_SaveGameTypeSlot.h"
#include "framework/S_SaveBuildStamp.h"
#include "framework/C_SaveGameManager.h"
// fast travel (playermodule; owned at C_PlayerModule+0x28)
#include "playermodule/S_FastTravelConfig.h"
#include "playermodule/C_FastTravel.h"

// ---- Tranche 6: RPG locations / effects / perks / rewards / causes + databasemodule ----
#include "framework/C_BaseModule.h"
#include "framework/I_BindableObject.h"
#include "framework/I_WUIDMappingProvider.h"
#include "framework/WUID.h"
#include "framework/fixed_t.h"
#include "xgenaimodule/I_SmartAreasManagerListener.h"
#include "databasemodule/C_DatabaseModule.h"
#include "databasemodule/C_ObjectDatabase.h"
#include "databasemodule/C_ObjectDatabaseBase.h"
#include "databasemodule/C_ObjectDatabaseIdIndexed.h"
#include "databasemodule/C_ObjectDatabaseKeyMultiIndexed.h"
#include "databasemodule/C_ObjectDatabaseManager.h"
#include "databasemodule/C_ObjectDatabaseSortedIdIndexed.h"
#include "databasemodule/C_ObjectTableDatabase.h"
#include "databasemodule/I_DatabaseModule.h"
#include "databasemodule/I_DynamicEnum.h"
#include "databasemodule/I_ObjectDatabase.h"
#include "rpgmodule/C_ActStaminaValueEffect.h"
#include "rpgmodule/C_AddBuffEffect.h"
#include "rpgmodule/C_AddItemEffect.h"
#include "rpgmodule/C_AddItemOnEquipBuffEffect.h"
#include "rpgmodule/C_AddPerkEffect.h"
#include "rpgmodule/C_AlcoholismValueEffect.h"
#include "rpgmodule/C_BloodEffect.h"
#include "rpgmodule/C_BuffOverridePerk.h"
#include "rpgmodule/C_BuffPerk.h"
#include "rpgmodule/C_Cause.h"
#include "rpgmodule/C_CodexPerk.h"
#include "rpgmodule/C_CombatTechniquePerk.h"
#include "rpgmodule/C_CompanionPerk.h"
#include "rpgmodule/C_ConstEffectVisitor.h"
#include "rpgmodule/C_DmgREffect.h"
#include "rpgmodule/C_DocumentRewardPerkDatabase.h"
#include "rpgmodule/C_DryHerbEffect.h"
#include "rpgmodule/C_Effect.h"
#include "rpgmodule/C_EffectVisitor.h"
#include "rpgmodule/C_FactionEffect.h"
#include "rpgmodule/C_FactionReputationEffect.h"
#include "rpgmodule/C_FactionReputationReward.h"
#include "rpgmodule/C_FoodValueEffect.h"
#include "rpgmodule/C_GenericReputationChangeCause.h"
#include "rpgmodule/C_HealthValueEffect.h"
#include "rpgmodule/C_ItemBloodEffect.h"
#include "rpgmodule/C_ItemDestroyedEffect.h"
#include "rpgmodule/C_ItemEffect.h"
#include "rpgmodule/C_ItemHealthValueEffect.h"
#include "rpgmodule/C_LearnPerkEffect.h"
#include "rpgmodule/C_Location2PerkDatabase.h"
#include "rpgmodule/C_LogPlayerReputationEffect.h"
#include "rpgmodule/C_MetaPerk.h"
#include "rpgmodule/C_OneShotSoundReportEffect.h"
#include "rpgmodule/C_POI.h"
#include "rpgmodule/C_POIType2PerkDatabase.h"
#include "rpgmodule/C_Perk.h"
#include "rpgmodule/C_Perk2PerkExclusivityDatabase.h"
#include "rpgmodule/C_PerkBuffDatabase.h"
#include "rpgmodule/C_PerkBuffOverrideDatabase.h"
#include "rpgmodule/C_PerkCodexDatabase.h"
#include "rpgmodule/C_PerkCombatTechniqueDatabase.h"
#include "rpgmodule/C_PerkCompanionDatabase.h"
#include "rpgmodule/C_PerkDatabase.h"
#include "rpgmodule/C_PerkRPGParamOverrideDatabase.h"
#include "rpgmodule/C_PerkRecipeDatabase.h"
#include "rpgmodule/C_PerkReward.h"
#include "rpgmodule/C_PerkScriptDatabase.h"
#include "rpgmodule/C_PerkSoulAbilityDatabase.h"
#include "rpgmodule/C_PerkUsedEffect.h"
#include "rpgmodule/C_PointShape.h"
#include "rpgmodule/C_PrepareFoodEffect.h"
#include "rpgmodule/C_PrepareItemEffect.h"
#include "rpgmodule/C_ProfilingLogEffect.h"
#include "rpgmodule/C_ProjectileStatusEffect.h"
#include "rpgmodule/C_RPGBase.h"
#include "rpgmodule/C_RPGLocation.h"
#include "rpgmodule/C_RPGLocationManager.h"
#include "rpgmodule/C_RPGParamOverridePerk.h"
#include "rpgmodule/C_RecipePerk.h"
#include "rpgmodule/C_RemoveAllBuffsByAITagEffect.h"
#include "rpgmodule/C_RemoveAllBuffsByGuidEffect.h"
#include "rpgmodule/C_RemoveItemOnEquipBuffEffect.h"
#include "rpgmodule/C_ReputationChangeDatabase.h"
#include "rpgmodule/C_ReputationConditionDatabase.h"
#include "rpgmodule/C_ReputationNotificationDatabase.h"
#include "rpgmodule/C_ResetNearbyPublicFriendsReputationEffect.h"
#include "rpgmodule/C_ResetPublicFriendsReputationEffect.h"
#include "rpgmodule/C_RestartStaminaRegenCooldownEffect.h"
#include "rpgmodule/C_RuntimeStateFlagEffect.h"
#include "rpgmodule/C_ScriptPerk.h"
#include "rpgmodule/C_SkillCheckResultEffect.h"
#include "rpgmodule/C_SkillXPEffect.h"
#include "rpgmodule/C_SocialClassDatabase.h"
#include "rpgmodule/C_SoulAbilityPerk.h"
#include "rpgmodule/C_SoulArchetypeDatabase.h"
#include "rpgmodule/C_SoulBleedingHealEffect.h"
#include "rpgmodule/C_SoulEffect.h"
#include "rpgmodule/C_SoulPlaceholderEffect.h"
#include "rpgmodule/C_SoulReputationEffect.h"
#include "rpgmodule/C_SoulReputationReward.h"
#include "rpgmodule/C_SoulStateEffect.h"
#include "rpgmodule/C_SoulStatsLogEffect.h"
#include "rpgmodule/C_SoulValueEffect.h"
#include "rpgmodule/C_StatXPEffect.h"
#include "rpgmodule/C_StealItemsEffect.h"
#include "rpgmodule/C_UnlockAchievementEffect.h"
#include "rpgmodule/C_VigourValueEffect.h"
#include "rpgmodule/E_SoulState.h"
#include "rpgmodule/I_Cause.h"
#include "rpgmodule/I_Location.h"
#include "rpgmodule/I_LocationListener.h"
#include "rpgmodule/I_POI.h"
#include "rpgmodule/I_POIShape.h"
#include "rpgmodule/I_RPGLocationManager.h"
#include "rpgmodule/I_Reward.h"
#include "rpgmodule/S_GenericReputationChangeData.h"
#include "rpgmodule/S_Perk.h"
#include "rpgmodule/S_PerkDefinitionId.h"
#include "rpgmodule/S_ProfilingLogPayload.h"
#include "rpgmodule/S_ReputationChange.h"
#include "rpgmodule/S_ReputationChangeRequest.h"
#include "rpgmodule/S_SocialClass.h"
#include "rpgmodule/S_SoulArchetype.h"

// ---- Tranche 7: conceptmodule node graph + tree databases + mapping-table rows ----
#include "conceptmodule/C_AutoTriggerable.h"
#include "conceptmodule/C_Effect.h"
#include "conceptmodule/C_Node.h"
#include "conceptmodule/C_PortRef.h"
#include "conceptmodule/C_SharedResource.h"
#include "conceptmodule/C_SoulEffect.h"
#include "conceptmodule/C_TypedArrayPortRef.h"
#include "conceptmodule/C_TypedPortRef.h"
#include "conceptmodule/I_Port.h"
#include "databasemodule/C_DynamicEnumManager.h"
#include "databasemodule/C_ObjectDatabaseDefaultKeyExtractor.h"
#include "databasemodule/C_ObjectDatabaseKeyIndexed.h"
#include "databasemodule/C_ObjectTreeDatabase.h"
#include "rpgmodule/C_BuffEffect.h"
#include "rpgmodule/C_FallDamageCause.h"
#include "rpgmodule/C_SoulStateEffectContextDatabase.h"
#include "rpgmodule/C_TemporaryFactionEffect.h"
#include "rpgmodule/S_DocumentRewardPerk.h"
#include "rpgmodule/S_FallDamageData.h"
#include "rpgmodule/S_Location2Perk.h"
#include "rpgmodule/S_POIType2Perk.h"
#include "rpgmodule/S_Perk2PerkExclusivity.h"
#include "rpgmodule/S_PerkBuff.h"
#include "rpgmodule/S_PerkBuffOverride.h"
#include "rpgmodule/S_PerkCodex.h"
#include "rpgmodule/S_PerkCombatTechnique.h"
#include "rpgmodule/S_PerkCompanion.h"
#include "rpgmodule/S_PerkRPGParamOverride.h"
#include "rpgmodule/S_PerkRecipe.h"
#include "rpgmodule/S_PerkScript.h"
#include "rpgmodule/S_PerkSoulAbility.h"
#include "rpgmodule/S_ReputationCondition.h"
#include "rpgmodule/S_ReputationNotification.h"

// ---- Tranche 8: playermodule script binds ----
#include "playermodule/C_FastTravelScriptBind.h"
#include "playermodule/C_ScriptBindMinigame.h"
#include "playermodule/C_ScriptBindSkipTime.h"
#include "playermodule/C_ScriptBind_Alchemy.h"
#include "playermodule/C_ScriptBind_Blacksmithing.h"
#include "playermodule/C_ScriptBind_Dice.h"
#include "playermodule/C_ScriptBind_ForgeBuilder.h"
#include "playermodule/C_ScriptBind_HoleDigging.h"
#include "playermodule/C_ScriptBind_Sharpening.h"
#include "playermodule/C_ScriptBind_ShootingContest.h"
#include "playermodule/C_ScriptBind_StoneThrowing.h"

// ---- Tranche 9: KCD2-new module roots ----
#include "conceptmodule/C_ConceptModule.h"
#include "musicmodule/C_MusicModule.h"
#include "xbehaviormodule/C_XBehaviorModule.h"

// ---- Tranche 10: combatmodule action system (framework action stack + module core +
//      enums/data + action leaves + triggers + subsystems) ----
#include "framework/I_Action.h"
#include "framework/I_ActionImpl.h"
#include "framework/C_Action.h"
#include "framework/C_ParamAction.h"
#include "animationmodule/I_SceneListener.h"
#include "animationmodule/I_AdbChangeListener.h"
#include "animationmodule/I_QueryableDatabase.h"
#include "animationmodule/C_AnimationDatabaseBase.h"
#include "animationmodule/C_AnimationDatabaseGenerated.h"
#include "animationmodule/C_ActionDatabaseGenerated.h"
#include "animationmodule/C_ObjectAnimationDatabaseGenerated.h"
#include "databasemodule/C_ObjectDatabaseGenerated.h"
#include "game/I_GameSideEffectCallback.h"
#include "combatmodule/C_CombatActionHelper.h"
#include "combatmodule/C_CombatActionFactoryBase.h"
#include "combatmodule/C_CombatActionAttackFactory.h"
#include "combatmodule/C_CombatDatabaseGenerated.h"
#include "combatmodule/C_CombatActionTrigger.h"
#include "combatmodule/C_CombatActorAction.h"
#include "combatmodule/C_CombatActorActionAttack.h"
#include "combatmodule/C_CombatActorActionBlock.h"
#include "combatmodule/C_CombatActorActionBlockTrigger.h"
#include "combatmodule/C_CombatActorActionDodge.h"
#include "combatmodule/C_CombatActorActionFailedAttack.h"
#include "combatmodule/C_CombatActorActionFreeBlock.h"
#include "combatmodule/C_CombatActorActionGuard.h"
#include "combatmodule/C_CombatActorActionGuardMovement.h"
#include "combatmodule/C_CombatActorActionGuardSyncMovement.h"
#include "combatmodule/C_CombatActorActionGuardVar.h"
#include "combatmodule/C_CombatActorActionHit.h"
#include "combatmodule/C_CombatActorActionPerfectBlock.h"
#include "combatmodule/C_CombatActorActionPerfectBlockBase.h"
#include "combatmodule/C_CombatActorActionPoseModifier.h"
#include "combatmodule/C_CombatActorActionRiderMovement.h"
#include "combatmodule/C_CombatActorActionStaticAttack.h"
#include "combatmodule/C_CombatActorActionSyncAttack.h"
#include "combatmodule/C_CombatActorActionSyncHit.h"
#include "combatmodule/C_CombatActorActionSyncPerfectBlock.h"
#include "combatmodule/C_CombatActorActionSyncPerfectBlockHit.h"
#include "combatmodule/C_CombatActorActionSyncTransition.h"
#include "combatmodule/C_CombatActorAnimatedAction.h"
#include "combatmodule/C_CombatActorHorsePullDown.h"
#include "combatmodule/C_CombatActorMercyKill.h"
#include "combatmodule/C_CombatActorParamAction.h"
#include "combatmodule/C_CombatAttackTypeData.h"
#include "combatmodule/C_CombatModule.h"
#include "combatmodule/C_CombatScene.h"
#include "combatmodule/C_CombatSlotTrigger.h"
#include "combatmodule/C_CombatTarget.h"
#include "combatmodule/C_CombatTrigger.h"
#include "combatmodule/C_CombatTriggerCombo.h"
#include "combatmodule/C_CombatTriggerPerfectBlock.h"
#include "combatmodule/C_CombatTriggerRiposte.h"
#include "combatmodule/C_CombatTriggerSyncPerfectBlock.h"
#include "combatmodule/C_CombatWeaponGroupData.h"
#include "combatmodule/C_CombatZoneData.h"
#include "combatmodule/E_CombatActionType.h"
#include "combatmodule/E_CombatAttackType.h"
#include "combatmodule/E_CombatInputClass.h"
#include "combatmodule/E_CombatSubsystem.h"
#include "combatmodule/E_CombatZoneId.h"
#include "combatmodule/E_CounterActionType.h"
#include "combatmodule/E_CombatAutomationActionKind.h"
#include "combatmodule/E_CombatAutomationDirectorState.h"
#include "combatmodule/E_CombatAutomationWeaponRequest.h"
#include "combatmodule/E_CombatAutomationZoneRequestedChange.h"
#include "combatmodule/E_CombatAutomationZoneState.h"
#include "combatmodule/I_CombatActionAttackHelperParams.h"
#include "combatmodule/I_CombatActionBlockHelperParams.h"
#include "combatmodule/I_CombatActionHelperAttackOwner.h"
#include "combatmodule/I_CombatActionHelperBlockOwner.h"
#include "combatmodule/I_CombatActor.h"
#include "combatmodule/I_CombatActorAction.h"
#include "combatmodule/I_CombatActorActionBlock.h"
#include "combatmodule/I_CombatActorActionPrivate.h"
#include "combatmodule/I_CombatActorHorsePullDown.h"
#include "combatmodule/I_CombatActorMercyKill.h"
#include "combatmodule/I_CombatAttackData.h"
#include "combatmodule/I_CombatCollisionProcessOwner.h"
#include "combatmodule/I_CombatAttackTypeData.h"
#include "combatmodule/I_CombatScene.h"
#include "combatmodule/I_CombatTarget.h"
#include "combatmodule/I_CombatWeaponGroupData.h"
#include "combatmodule/I_CombatZoneData.h"
#include "combatmodule/S_AttackCandidateResultHolder.h"
#include "combatmodule/S_CombatActionAttackQueryData.h"
#include "combatmodule/S_CombatActorActionAttackParams.h"
#include "combatmodule/S_CombatActorActionBlockParams.h"
#include "combatmodule/S_CombatActorActionBlockTriggerParams.h"
#include "combatmodule/S_CombatActorActionDodgeParams.h"
#include "combatmodule/S_CombatActorActionFailedAttackParams.h"
#include "combatmodule/S_CombatActorActionFreeBlockParams.h"
#include "combatmodule/S_CombatActorActionGuardMovementParams.h"
#include "combatmodule/S_CombatActorActionGuardParams.h"
#include "combatmodule/S_CombatActorActionGuardSyncMovementParams.h"
#include "combatmodule/S_CombatActorActionGuardVarParams.h"
#include "combatmodule/S_CombatActorActionHitParams.h"
#include "combatmodule/S_CombatActorActionPerfectBlockBaseParams.h"
#include "combatmodule/S_CombatActorActionPerfectBlockParams.h"
#include "combatmodule/S_CombatActorActionPoseModifierParams.h"
#include "combatmodule/S_CombatActorActionStaticAttackParams.h"
#include "combatmodule/S_CombatActorActionSyncAttackParams.h"
#include "combatmodule/S_CombatActorActionSyncHitParams.h"
#include "combatmodule/S_CombatActorActionSyncPerfectBlockHitParams.h"
#include "combatmodule/S_CombatActorActionSyncPerfectBlockParams.h"
#include "combatmodule/S_CombatActorActionSyncTransitionParams.h"
#include "combatmodule/S_CombatQueryData.h"
#include "combatmodule/S_CombatSettings.h"
#include "combatmodule/S_ReactionWeights.h"

// ---- Tranche 11: combatmodule data verticals (table row structs + Data classes;
//      recovered from the C_CombatDatabase<...> instantiation parse/register slots) ----
#include "combatmodule/E_CombatTag.h"
#include "combatmodule/S_KeyValueTableRow.h"
#include "combatmodule/C_KeyValueData.h"
#include "combatmodule/C_CombatActionTriggerData.h"
#include "combatmodule/C_CombatActionTypeData.h"
#include "combatmodule/C_CombatActionTypeDataDestination.h"
#include "combatmodule/C_CombatActionTypeDataSource.h"
#include "combatmodule/C_CombatActionTypeGroupData.h"
#include "combatmodule/C_CombatAttackConfigData.h"
#include "combatmodule/C_CombatAttackHitStatisticsData.h"
#include "combatmodule/C_CombatDamageTypeMappingData.h"
#include "combatmodule/C_CombatGuardStanceData.h"
#include "combatmodule/C_CombatGuardTypeData.h"
#include "combatmodule/C_CombatHitOriginData.h"
#include "combatmodule/C_CombatHitTypeData.h"
#include "combatmodule/C_CombatInputClassData.h"
#include "combatmodule/C_CombatNativeGuardZoneData.h"
#include "combatmodule/C_CombatSideData.h"
#include "combatmodule/C_CombatTagData.h"
#include "combatmodule/C_CombatWeaponCombinationData.h"
#include "combatmodule/C_CombatWeaponGroupToClassData.h"
#include "combatmodule/C_CombatZoneConfigData.h"
#include "combatmodule/C_CombatZoneDistanceData.h"
#include "combatmodule/C_CombatZoneMappingData.h"
#include "combatmodule/S_CombatActionTriggerDBData.h"
#include "combatmodule/S_CombatActionTypeGroupDBData.h"
#include "combatmodule/S_CombatActionTypeTableRow.h"
#include "combatmodule/S_CombatAttackConfigTableRow.h"
#include "combatmodule/S_CombatAttackHitStatisticsDBData.h"
#include "combatmodule/S_CombatAttackTypeTableRow.h"
#include "combatmodule/S_CombatDamageTypeMappingDBData.h"
#include "combatmodule/S_CombatGuardStanceTableRow.h"
#include "combatmodule/S_CombatGuardTypeTableRow.h"
#include "combatmodule/S_CombatHitOriginDBData.h"
#include "combatmodule/S_CombatHitTypeDBData.h"
#include "combatmodule/S_CombatInputClassTableRow.h"
#include "combatmodule/S_CombatNativeGuardZoneTableRow.h"
#include "combatmodule/S_CombatSideDBData.h"
#include "combatmodule/S_CombatTagTableRow.h"
#include "combatmodule/S_CombatWeaponCombinationDBData.h"
#include "combatmodule/S_CombatWeaponGroupDBData.h"
#include "combatmodule/S_CombatWeaponGroupToClassDBData.h"
#include "combatmodule/S_CombatZoneConfigTableRow.h"
#include "combatmodule/S_CombatZoneDataDBData.h"
#include "combatmodule/S_CombatZoneDistanceDBData.h"
#include "combatmodule/S_CombatZoneMappingTableRow.h"

// ---- Tranche 12: guimodule spine (wave G2) + flash-infra support interfaces.
//      Flash vtable maps live in the Offsets/vtables section above. ----
#include "framework/I_SourceMonitorListener.h"
#include "playermodule/I_UIActionHintManager.h"
#include "guimodule/C_UIBase.h"
#include "guimodule/C_UIFlashBase.h"
#include "guimodule/C_UICommonEventHandler.h"
#include "guimodule/I_UIMenu.h"
#include "guimodule/C_UIMenuBase.h"
#include "guimodule/C_UIPhotomodeMenu.h"
#include "guimodule/C_UISaveLoad.h"
#include "guimodule/C_UISettings.h"
#include "guimodule/C_UIMenu.h"
#include "guimodule/C_ScriptBindMap.h"
#include "guimodule/C_ScriptBindUI.h"
#include "guimodule/C_UIActionHintManager.h"
#include "guimodule/C_UIBuffsManager.h"
#include "guimodule/C_UIFullUIModeHelper.h"
#include "guimodule/C_UILightsManager.h"
#include "guimodule/C_UIQAMSelectionHandler.h"
#include "guimodule/C_GUIModule.h"

// ---- Tranche 13: guimodule wave G3b -- HUD family + KCD1-parity leaves,
//      cross-module UI interfaces, HUD-visibility (letterbox) machinery. ----
#include "framework/E_HudElements.h"
#include "framework/I_EventLogListener.h"
#include "framework/I_UIHudBubbles.h"
#include "framework/I_UIHudCrimeList.h"
#include "framework/I_UIHudEvents.h"
#include "framework/I_UIHudMask.h"
#include "framework/I_UIHudMessages.h"
#include "questmodule/I_UIHudEventsQuest.h"
#include "dialogmodule/I_UIHudInteractiveDialog.h"
#include "dialogmodule/I_UISubtitles.h"
#include "playermodule/I_UIHudHints.h"
#include "playermodule/I_UIKeybinds.h"
#include "playermodule/I_UIGameOver.h"
#include "guimodule/I_UIBuffsListener.h"
#include "guimodule/I_UIDragAndDropViewer.h"
#include "guimodule/C_UIModalDialogItem.h"
#include "guimodule/C_UIModalDialogInfo.h"
#include "guimodule/C_UIHudAdaptiveGroup.h"
#include "guimodule/C_UIHudAdaptive.h"
#include "guimodule/C_UIHudBubbles.h"
#include "guimodule/C_UIHudBuffs.h"
#include "guimodule/C_UIHudCrimeList.h"
#include "guimodule/C_UIHudEvents.h"
#include "guimodule/C_UIHudHints.h"
#include "guimodule/C_UIHudInteractiveDialog.h"
#include "guimodule/C_UIHudMask.h"
#include "guimodule/C_UIHudMessages.h"
#include "guimodule/C_UIHudQAM.h"
#include "guimodule/C_UIHudStates.h"
#include "guimodule/C_UIQuestLog.h"
#include "guimodule/C_UIKeybinds.h"
#include "guimodule/C_UILoadingScreen.h"
#include "guimodule/C_UIGameOver.h"
#include "guimodule/C_UISubtitles.h"

// ---- Tranche 14: guimodule wave G3a -- map/navigation vertical
//      (C_UIMap demoted to C_UIApse sub-component; typed I_UIFastTravel). ----
#include "xgenaimodule/I_AreaTracker.h"
#include "xgenaimodule/I_ObjectManagerBaseListener.h"
#include "playermodule/I_UIFastTravel.h"
#include "playermodule/I_FogOfWarListener.h"
#include "guimodule/C_UIFlashObject.h"
#include "guimodule/C_UIFlashDynTextureHelper.h"
#include "guimodule/S_EntityMapMark.h"
#include "guimodule/E_ConceptMarkerType.h"
#include "guimodule/C_CompassMark.h"
#include "guimodule/C_CheckpointMark.h"
#include "guimodule/C_UICompass.h"
#include "guimodule/C_UIExtendedInfo.h"
#include "guimodule/C_UITreeList.h"
#include "guimodule/C_UIModalDialogQuestion.h"
#include "guimodule/C_UIModalDialogRandomEvent.h"
#include "guimodule/C_UIMapContent.h"
#include "guimodule/C_UIMapCloudAtlas.h"
#include "guimodule/C_UIMap.h"
#include "guimodule/C_ShowMapMarker.h"

// ---- Tranche 15: guimodule wave G4a -- Apse menu/character hub + modal dialogs
//      (orchestrator-composed from analysis/guimodule_port/apse.md). ----
#include "framework/I_UIApse.h"
#include "framework/I_UICamera.h"
#include "guimodule/I_UIModalDialogListener.h"
#include "guimodule/I_UIDragAndDropTarget.h"
#include "guimodule/I_UIItemContext.h"
#include "guimodule/C_UIModalDialogAmount.h"
#include "guimodule/C_UIModalDialogHealing.h"
#include "guimodule/C_UISelectedItemsReporter.h"
#include "guimodule/C_UIModalDialogCombine.h"
#include "guimodule/C_UIReputation.h"
#include "guimodule/C_UIDragAndDropHelper.h"
#include "guimodule/C_UICodexCraftingContent.h"
#include "guimodule/C_UIApseSoulProperties.h"
#include "guimodule/C_UIApseBuffs.h"
#include "guimodule/C_UIApseStatistics.h"
#include "guimodule/C_UIApseQAMInteraction.h"
#include "guimodule/C_UIApseCharacterContent.h"
#include "guimodule/C_UICharacterSlots.h"
#include "guimodule/C_UIApseCharacterSlots.h"
#include "guimodule/C_UICharacterBase.h"
#include "guimodule/C_UIApseCharacter.h"
#include "guimodule/C_UIInventoryBase.h"
#include "guimodule/C_UIApseInventory.h"
#include "guimodule/C_UIApsePlayer.h"
#include "guimodule/C_UIApseCodex.h"
#include "guimodule/C_UIApseCrafting.h"
#include "guimodule/C_UIApseCamera.h"
#include "guimodule/C_UIApse.h"

// ---- Tranche 16: guimodule wave G4d -- the 12 guimodule databases (7 table verticals
//      on C_ObjectTableDatabase + 4 menu tree verticals; C_CutsceneDatabase deferred to
//      the G4c tranche pending its second-base identity). Composed from
//      analysis/guimodule_port/gui_databases.md. ----
#include "framework/C_LocalizedString.h"
#include "guimodule/E_ButtonId.h"
#include "guimodule/E_ChoiceName.h"
#include "guimodule/E_ConfirmationId.h"
#include "guimodule/E_MenuPage.h"
#include "guimodule/C_UIMenuButton.h"
#include "guimodule/C_UIMenuChoice.h"
#include "guimodule/C_UIMenuConfirmation.h"
#include "guimodule/C_UIMenuPage.h"
#include "guimodule/S_CreditsLayoutDBData.h"
#include "guimodule/S_CreditsLayout.h"
#include "guimodule/S_CreditsPeopleDBData.h"
#include "guimodule/S_CreditsPeople.h"
#include "guimodule/S_CreditsRole2LanguageExclDBData.h"
#include "guimodule/S_CreditsRole2LanguageExcl.h"
#include "guimodule/S_CreditsRoleDBData.h"
#include "guimodule/S_CreditsRole.h"
#include "guimodule/S_LocalMapDBData.h"
#include "guimodule/S_LocalMap.h"
#include "guimodule/S_MapLabelDBData.h"
#include "guimodule/S_MapLabel.h"
#include "guimodule/S_VideoLanguageDBData.h"
#include "guimodule/S_VideoLanguage.h"
#include "guimodule/C_CreditsLayoutDatabase.h"
#include "guimodule/C_CreditsPeopleDatabase.h"
#include "guimodule/C_CreditsRole2LanguageExclDatabase.h"
#include "guimodule/C_CreditsRoleDatabase.h"
#include "guimodule/C_LocalMapDatabase.h"
#include "guimodule/C_MapLabelDatabase.h"
#include "guimodule/C_VideoLanguageDatabase.h"
#include "guimodule/C_MenuButtonDatabase.h"
#include "guimodule/C_MenuChoiceDatabase.h"
#include "guimodule/C_MenuConfirmationDatabase.h"
#include "guimodule/C_MenuPageDatabase.h"

// ---- Tranche 17: guimodule wave G4b -- the C_UIFlash* serialization-record family
//      (65 C_UIFlashObject-derived leaves; composed from
//      analysis/guimodule_port/flash_leaves.md). ----
// direct leaves
#include "guimodule/C_UIFlashBodyPart.h"
#include "guimodule/C_UIFlashCharacterSlotItem.h"
#include "guimodule/C_UIFlashCharacterSoulProperty.h"
#include "guimodule/C_UIFlashCharacterWeaponStatSub.h"
#include "guimodule/C_UIFlashCharacterArmorStatSub.h"
#include "guimodule/C_UIFlashContentCodexRecord.h"
#include "guimodule/C_UIFlashContentRecipeHerb.h"
#include "guimodule/C_UIFlashProsBanner.h"
#include "guimodule/C_UIFlashHardcorePerk.h"
#include "guimodule/C_UIFlashHorseInspect.h"
#include "guimodule/C_UIFlashHudCrimeStolenItem.h"
#include "guimodule/C_UIFlashHudCrime.h"
#include "guimodule/C_UIFlashInfoBuff.h"
#include "guimodule/C_UIFlashInfoReputation.h"
#include "guimodule/C_UIFlashInfoSoulProperty.h"
#include "guimodule/C_UIFlashListBuff.h"
#include "guimodule/C_UIFlashListObjective.h"
#include "guimodule/C_UIFlashListPerk.h"
#include "guimodule/C_UIFlashListQuest.h"
#include "guimodule/C_UIFlashListRecipe.h"
#include "guimodule/C_UIFlashListReputation.h"
#include "guimodule/C_UIFlashListSoulProperty.h"
#include "guimodule/C_UIFlashListStatistics.h"
#include "guimodule/C_UIFlashListMapLegendItem.h"
#include "guimodule/C_UIFlashListMapLegendUniqueItem.h"
#include "guimodule/C_UIFlashMapLabel.h"
#include "guimodule/C_UIFlashMapLocalMap.h"
#include "guimodule/C_UIFlashMapPoiMarker.h"
#include "guimodule/C_UIFlashMapQuestMarker.h"
#include "guimodule/C_UIFlashPickpocketingItem.h"
#include "guimodule/C_UIFlashReward.h"
// container leaves (elements included above)
#include "guimodule/C_UIFlashCharacterArmorStat.h"
#include "guimodule/C_UIFlashCharacterWeaponStat.h"
#include "guimodule/C_UIFlashCharacterSlot.h"
#include "guimodule/C_UIFlashCreditsPeople.h"
#include "guimodule/C_UIFlashCreditsRole.h"
#include "guimodule/C_UIFlashDiaryQuest.h"
#include "guimodule/C_UIFlashHudQAMSlotItem.h"
#include "guimodule/C_UIFlashHudQAMSlot.h"
#include "guimodule/C_UIFlashInfoCombo.h"
#include "guimodule/C_UIFlashInfoPerk.h"
#include "guimodule/C_UIFlashListCodexRecord.h"
#include "guimodule/C_UIFlashListCombo.h"
#include "guimodule/C_UIFlashListCombosGroup.h"
#include "guimodule/C_UIFlashListStatisticsGroup.h"
#include "guimodule/C_UIFlashContentRecipeAlchemy.h"
#include "guimodule/C_UIFlashContentRecipeBlacksmith.h"
// InfoItem subtree
#include "guimodule/C_UIFlashInfoItem.h"
#include "guimodule/C_UIFlashInfoItemAmmo.h"
#include "guimodule/C_UIFlashInfoItemQAMContainer.h"
#include "guimodule/C_UIFlashInfoItemDestructible.h"
#include "guimodule/C_UIFlashInfoItemFood.h"
#include "guimodule/C_UIFlashInfoItemDocument.h"
#include "guimodule/C_UIFlashInfoItemSkillbook.h"
#include "guimodule/C_UIFlashInfoItemEquippable.h"
#include "guimodule/C_UIFlashInfoItemArmor.h"
#include "guimodule/C_UIFlashInfoItemWeapon.h"
#include "guimodule/C_UIFlashInfoItemMelee.h"
#include "guimodule/C_UIFlashInfoItemMissile.h"
#include "guimodule/C_UIFlashInfoItemOffHand.h"
// ListItem subtree
#include "guimodule/C_UIFlashListItem.h"
#include "guimodule/C_UIFlashListItemApse.h"
#include "guimodule/C_UIFlashListItemSelection.h"
#include "guimodule/C_UIFlashListItemSelectionCost.h"
#include "guimodule/C_UIFlashListItemTrader.h"

// ---- Tranche 18: guimodule wave G4c -- cutscene/fader subsystem + concept-graph
//      trigger nodes + C_CutsceneDatabase (composed from
//      analysis/guimodule_port/cutscene_fader.md). ----
// conceptmodule/framework support
#include "conceptmodule/S_Trigger.h"
#include "conceptmodule/C_RuntimeState.h"
#include "conceptmodule/C_EventNode.h"
#include "conceptmodule/C_StateProxy.h"
#include "framework/E_UIApseView.h"
#include "guimodule/E_BlockUINotificationType.h"
#include "guimodule/E_CutsceneType.h"
#include "guimodule/E_UIApseState.h"
#include "guimodule/E_UICharacterState.h"
#include "entitymodule/E_InteractionType.h"
#include "entitymodule/E_QuickSlotSpec.h"
#include "entitymodule/E_AuxLightType.h"
#include "dialogmodule/E_DialogCameraType.h"
#include "playermodule/E_MinigameType.h"
#include "playermodule/E_OutfitId.h"
#include "rpgmodule/E_CompanionEvent.h"
// interfaces
#include "guimodule/I_Cutscene.h"
#include "guimodule/I_InteractiveScenePlayer.h"
#include "guimodule/I_CutsceneChangeListener.h"
#include "guimodule/I_FaderController.h"
#include "guimodule/I_FaderListener.h"
#include "game/I_SkipEventProvider.h"
#include "Offsets/vtables/ITrackEventListener.h"
// cutscene family
#include "guimodule/C_CreditsCutscene.h"
#include "guimodule/C_TextCutscene.h"
#include "guimodule/C_FastTravelCutscene.h"
#include "guimodule/C_SkipTimeCutscene.h"
#include "guimodule/C_FaderCutscene.h"
#include "guimodule/C_RenderedCutscene.h"
#include "guimodule/C_TrackViewBase.h"
#include "guimodule/C_TrackViewCutscene.h"
#include "guimodule/C_IngameCutscene.h"
#include "guimodule/C_CutscenePlayer.h"
#include "guimodule/S_CutsceneEventDesc.h"
#include "guimodule/C_CutsceneEvent.h"
#include "guimodule/S_CutsceneProfile.h"
#include "guimodule/C_CutsceneHandler.h"
#include "guimodule/C_FaderController.h"
#include "guimodule/C_FaderSuspend.h"
// trigger nodes
#include "guimodule/C_ApseViewTrigger.h"
#include "guimodule/C_BlockUINotifications.h"
#include "guimodule/C_InfiniteHoldInteractionTrigger.h"
#include "guimodule/C_InteractorOverride.h"
#include "guimodule/C_PlayTrackView.h"
// the deferred G4d MI database (second base resolved by G4c Part D)
#include "guimodule/C_CutsceneDatabase.h"

// ---- Tranche 19: small-modules wave -- environmentmodule (23) + questmodule (14) +
//      wh::shared streams (8) + the conceptmodule bases they stand on (composed from
//      analysis/small_modules_port/env_quest_shared.md). The three env databases' data-ns
//      row structs (C_PickableAreaData/S_PickableAreaRow, S_PickableAreaMaterial(+DBData),
//      S_WeatherProfileData) are forward-declared only -- layouts come with the
//      generated-tables pass. ----
// engine-interface stubs + framework support
#include "Offsets/vtables/CFlowBaseNode.h"
#include "Offsets/vtables/IMergeMeshStreamListener.h"
#include "Offsets/vtables/IRenderNodeInstanceStreamingCallback.h"
#include "framework/I_EEFunction.h"
#include "framework/S_ResourceHandle.h"
// conceptmodule bases (unblock the quest node family)
#include "conceptmodule/C_ModuleBase.h"
#include "conceptmodule/C_TemplatedNode.h"
#include "conceptmodule/C_NodeManager.h"
// wh::shared stream stack
#include "shared/I_InputStream.h"
#include "shared/I_OutputStream.h"
#include "shared/I_SeekableOutputStream.h"
#include "shared/I_MemoryOutputStream.h"
#include "shared/C_MemoryIOStream.h"
#include "shared/C_FragmentedMemoryIOStream.h"
#include "shared/I_CrashHandler.h"
#include "shared/C_RegularGridObjectWrapperBase.h"
// environmentmodule
#include "environmentmodule/I_VisualEffect.h"
#include "environmentmodule/I_RespawnManager.h"
#include "environmentmodule/IWeatherSystem.h"
#include "environmentmodule/C_VisualEffect.h"
#include "environmentmodule/C_TimeOfDayProfile.h"
#include "environmentmodule/C_FunctionIsRaining.h"
#include "environmentmodule/C_StreamingHelper.h"
#include "environmentmodule/C_VisualEffectManager.h"
#include "environmentmodule/C_LightEffectVec.h"
#include "environmentmodule/C_MaterialEffectVec.h"
#include "environmentmodule/C_MaterialEffectFloat.h"
#include "environmentmodule/CFlowNode_Weather.h"
#include "environmentmodule/CFlowNodeHDRPreset.h"
#include "environmentmodule/C_SunEffect.h"
#include "environmentmodule/C_MoonEffect.h"
#include "environmentmodule/C_Rain.h"
#include "environmentmodule/C_ScriptBindEnvironment.h"
#include "environmentmodule/C_RespawnManager.h"
#include "environmentmodule/C_WeatherSystem.h"
#include "environmentmodule/C_PickableAreaDatabase.h"
#include "environmentmodule/C_PickableAreaMaterialDatabase.h"
#include "environmentmodule/C_WeatherProfileDatabase.h"
#include "environmentmodule/C_EnvironmentModule.h"
// questmodule
#include "questmodule/S_Tracker.h"
#include "questmodule/E_QuestProgress.h"
#include "questmodule/C_LogBase.h"
#include "questmodule/C_EnumLog.h"
#include "questmodule/C_Log.h"
#include "questmodule/C_Gameplay.h"
#include "questmodule/C_Quest.h"
#include "questmodule/C_ActivityUnit.h"
#include "questmodule/C_Objective.h"
#include "questmodule/C_ActivityCollection.h"
#include "questmodule/C_ActivityType.h"
#include "questmodule/C_QuestManager.h"
#include "questmodule/C_ActivityManager.h"
#include "questmodule/C_QuestModule.h"

// ---- Tranche 20: dialogmodule -- the 33 @dialogmodule@wh@@ classes + the
//      wh::dialogmodule::data nested types (composed from
//      analysis/small_modules_port/dialogmodule.md). C_DialogAnimAction is DEFERRED
//      (needs the unported animationmodule C_AnimActionBase/C_CallbackAction Mannequin
//      chain). I_UIHudInteractiveDialog/I_UISubtitles were already in tranche 13. ----
// engine-interface mirror + cross-module interfaces
#include "Offsets/vtables/IUIActionListener.h"
#include "framework/I_ContextUserData.h"
#include "entitymodule/I_ActorSpeakCallback.h"
#include "xgenaimodule/I_IntermissionInvoker.h"
// dialogmodule interfaces
#include "dialogmodule/I_DialogCommand.h"
#include "dialogmodule/I_DialogCommandReceiver.h"
#include "dialogmodule/I_DialogInteractionCallback.h"
#include "dialogmodule/I_Dialog.h"
#include "dialogmodule/I_TestDialog.h"
#include "dialogmodule/I_DialogueExtension.h"
#include "dialogmodule/I_DialogCameraManager.h"
// command hierarchy (wh::dialogmodule::data)
#include "dialogmodule/C_Command.h"
#include "dialogmodule/C_ShowActorCommand.h"
#include "dialogmodule/C_HideActorCommand.h"
#include "dialogmodule/C_CameraCommand.h"
#include "dialogmodule/C_MoodCommand.h"
#include "dialogmodule/C_FacialMoodCommand.h"
#include "dialogmodule/C_PointAtCommand.h"
#include "dialogmodule/C_ScriptCommand.h"
#include "dialogmodule/C_LookAtCommand.h"
#include "dialogmodule/C_PropCommand.h"
#include "dialogmodule/C_InstantPropCommand.h"
#include "dialogmodule/C_AnimationPropCommand.h"
#include "dialogmodule/C_AnimationCommand.h"
#include "dialogmodule/C_AnimationHeadCommand.h"
// data graph
#include "dialogmodule/S_DialogParams.h"
#include "dialogmodule/S_Response.h"
#include "dialogmodule/S_Port.h"
#include "dialogmodule/S_IncludedDecisionAlias.h"
#include "dialogmodule/S_FastForwardRequest.h"
#include "dialogmodule/S_FastForwardRequestForAll.h"
#include "dialogmodule/S_FastForwardRequestForRole.h"
#include "dialogmodule/C_Decision.h"
#include "dialogmodule/C_Dialogue.h"
#include "dialogmodule/C_Sequence.h"
#include "dialogmodule/C_DialogueProp.h"
#include "dialogmodule/C_DialogueSequenceHolder.h"
#include "dialogmodule/C_DialogueNode.h"
#include "dialogmodule/C_FaderDialogueNode.h"
#include "dialogmodule/C_ForcedDialogueNode.h"
#include "dialogmodule/C_DialogueWrapper.h"
// expression-engine functions
#include "dialogmodule/C_DialogueNodeEEFunction.h"
#include "dialogmodule/C_FunctionPort.h"
#include "dialogmodule/C_FunctionEnum.h"
#include "dialogmodule/C_FunctionSequenceUsed.h"
#include "dialogmodule/C_FunctionThisSequenceUsed.h"
#include "dialogmodule/C_FunctionExtensionAccepted.h"
#include "dialogmodule/C_DialogFunctionExpression.h"
// databases (rows + DBData/preprocessor tags + the 5 DB classes + data manager)
#include "dialogmodule/S_DialogueFunction.h"
#include "dialogmodule/S_DialogueFunctionsDBData.h"
#include "dialogmodule/S_LookAtOffset.h"
#include "dialogmodule/S_DialogueDubbing.h"
#include "dialogmodule/S_DialogueAttachment.h"
#include "dialogmodule/S_DialogueAttachmentDBData.h"
#include "dialogmodule/C_DialogueAttachmentPreprocessor.h"
#include "dialogmodule/S_DialogueTiming.h"
#include "dialogmodule/S_DialogueTimingDBData.h"
#include "dialogmodule/C_DialogueTimingPreprocessor.h"
#include "dialogmodule/C_DialogueFunctionsDatabase.h"
#include "dialogmodule/C_DialogueDubbingDatabase.h"
#include "dialogmodule/C_LookAtOffsetDatabase.h"
#include "dialogmodule/C_DialogueAttachmentDatabaseGenerated.h"
#include "dialogmodule/C_DialogueTimingDatabaseGenerated.h"
#include "dialogmodule/C_DialogueDataManager.h"
// Mannequin procedural clip
#include "dialogmodule/S_DialogueAttachmentProceduralParams.h"
#include "dialogmodule/C_DialogueAttachmentProceduralClip.h"
// cameras
#include "dialogmodule/C_DialogCamera.h"
#include "dialogmodule/C_AnimatedCamera.h"
#include "dialogmodule/C_DialogCameraManager.h"
// extensions
#include "dialogmodule/C_DialogueHaggleExtension.h"
#include "dialogmodule/C_DialogueBarberExtension.h"
#include "dialogmodule/C_DialogueShieldPaintingExtension.h"
#include "dialogmodule/C_DialogueMapPlayerPositionExtension.h"
#include "dialogmodule/C_BarberExtensionController.h"
// runtime + binds
#include "dialogmodule/C_DialogInteraction.h"
#include "dialogmodule/C_PlayerDialogController.h"
#include "dialogmodule/C_DialogInstance.h"
#include "dialogmodule/C_ScriptBindDialog.h"
// spine
#include "dialogmodule/C_DialogManager.h"
#include "dialogmodule/C_DialogModule.h"

// ---- Tranche 21: xgenaimodule wave G1 -- module spine + singletons hub +
//      RPG perception helper + the two Lua scriptbinds + the savegame Patch trio
//      (composed from analysis/xgenaimodule_port/G1_dossier.md; Patch slot split
//      3+3+0 and hub slot 1 = C_AIObjectManager per G2_dossier.md corrections). ----
#include "framework/I_Patch.h"
#include "xgenaimodule/I_XGenAIModulePatch.h"
#include "xgenaimodule/C_Patch1_3.h"
#include "xgenaimodule/I_RPGPerceptionHelper.h"
#include "xgenaimodule/S_RPGPerceptionHelper.h"
#include "xgenaimodule/I_XGenAIModuleSingletons.h"
#include "xgenaimodule/C_XGenAIModuleSingletons.h"
#include "xgenaimodule/C_ScriptBindXGenAIModule.h"
#include "xgenaimodule/C_ScriptBindSmartObject.h"
#include "xgenaimodule/C_XGenAIModule.h"

// ---- Tranche 22: xgenaimodule wave G2 -- the AI object-model spine (C_AIObject ->
//      C_NPC), the I_AIPuppet hierarchy, the embedded ownership components, the
//      message system, and the three managers (composed from
//      analysis/xgenaimodule_port/G2_dossier.md + G2_supplement.md). ----
// mixins
#include "xgenaimodule/I_RWLocked.h"
#include "xgenaimodule/I_XGenAINPC.h"
// puppets (separate hierarchy; C_AIObject holds an I_AIPuppet* at +0x18)
#include "xgenaimodule/I_AIPuppet.h"
#include "xgenaimodule/C_CachedPuppet.h"
#include "xgenaimodule/C_AIPuppet.h"
#include "xgenaimodule/C_SOPuppet.h"
#include "xgenaimodule/C_ParticleEffectPuppet.h"
#include "xgenaimodule/C_GeneratedSOPuppet.h"
#include "xgenaimodule/C_PuppetAdapter.h"
#include "xgenaimodule/C_FormationAnchorPuppet.h"
#include "xgenaimodule/C_FormationSpinePointPuppet.h"
#include "xgenaimodule/C_PerceptibleVolumePuppet.h"
#include "xgenaimodule/C_InventoryPuppet.h"
#include "xgenaimodule/C_ItemPuppet.h"
// ownership components (embedded/heap; exposed via spine vtable slot 11)
#include "xgenaimodule/I_Ownership.h"
#include "xgenaimodule/C_Ownership.h"
#include "xgenaimodule/C_ItemOwnership.h"
#include "xgenaimodule/C_InventoryOwnership.h"
#include "xgenaimodule/C_ShopInventoryOwnership.h"
#include "xgenaimodule/C_HorseInventoryOwnership.h"
#include "xgenaimodule/C_NoOwnerOwnership.h"
#include "xgenaimodule/C_EmptyOwnership.h"
// the spine
#include "xgenaimodule/C_AIObject.h"
#include "xgenaimodule/C_LinkableObject.h"
#include "xgenaimodule/C_MessageCapableObject.h"
#include "xgenaimodule/C_IntelligentObject.h"
#include "xgenaimodule/I_NPC.h"
#include "xgenaimodule/C_NPC.h"
// message system
#include "xgenaimodule/I_MessageDispatcher.h"
#include "xgenaimodule/C_NPCMessageDispatcher.h"
#include "xgenaimodule/C_MessageInbox.h"
// managers
#include "xgenaimodule/I_DebugDraw.h"
#include "xgenaimodule/I_NPCManager.h"
#include "xgenaimodule/I_XGenAINPCManager.h"
#include "xgenaimodule/C_AIObjectManager.h"
#include "xgenaimodule/C_MessageCapableObjectManager.h"
#include "xgenaimodule/C_NPCManager.h"

// ---- Tranche 23: xgenaimodule wave G3 -- linkables/relationship graph,
//      perception/stealth, hearing/sound propagation, and the crime system
//      (composed from analysis/xgenaimodule_port/g3_dump_*.txt).  Deferred:
//      C_PerceptibleVolumeEffect, C_PerceptionTrigger, C_LODAgentPerceptibleVolume
//      (conceptmodule::C_Effect / trigger chains); no BT-filter-fleet headers. ----
// cross-module bases new in this tranche
#include "playermodule/I_Shelver.h"
#include "entitymodule/I_WorldInventoryListener.h"
// linkable graph: edges + query system
#include "xgenaimodule/S_LinkEdge.h"
#include "xgenaimodule/S_VirtualLinkEdge.h"
#include "xgenaimodule/I_LinkNetworkQuerySystem.h"
#include "xgenaimodule/C_LinkNetworkQuerySystem.h"
// linkable managers
#include "xgenaimodule/C_ObjectManagerProxyStorage.h"
#include "xgenaimodule/C_LinkModificationManager.h"
#include "xgenaimodule/C_LinkablesManager.h"
#include "xgenaimodule/C_DynamicLinkablesManager.h"
// dynamic linkable fleet
#include "xgenaimodule/C_DynamicLinkableObject.h"
#include "xgenaimodule/C_DynamicLinkableObjectWithOwnership.h"
#include "xgenaimodule/C_RemoteDynamicLinkableObject.h"
#include "xgenaimodule/C_RemoteDynamicLinkableObjectWithOwnership.h"
#include "xgenaimodule/C_AISlot.h"
// holders + entity extension
#include "xgenaimodule/I_LinkableObjectHolder.h"
#include "xgenaimodule/C_LinkableObjectHolder.h"
#include "xgenaimodule/C_LinkableObjectExtension.h"
// perception objects
#include "xgenaimodule/C_PerceptionObject.h"
#include "xgenaimodule/C_PerceptibleObject.h"
#include "xgenaimodule/C_StatePerceptibleObject.h"
#include "xgenaimodule/C_PerceptorObject.h"
#include "xgenaimodule/C_PerceptibleRefPoint.h"
#include "xgenaimodule/C_OrientedPerceptibleRefPoint.h"
// perceptible volumes
#include "xgenaimodule/C_PerceptibleVolume.h"
#include "xgenaimodule/C_PerceptibleVolumeCylinder.h"
// perception listeners + managers
#include "xgenaimodule/C_PerceptionItemListener.h"
#include "xgenaimodule/I_RandomEventPerception.h"
#include "xgenaimodule/C_RandomEventPerception.h"
#include "xgenaimodule/C_PerceptibleVolumeManager.h"
#include "xgenaimodule/C_RecognizingThresholdManager.h"
#include "xgenaimodule/C_PerceptionManager.h"
// stealth
#include "xgenaimodule/I_StealthWatcher.h"
#include "xgenaimodule/C_StealthWatcher.h"
// hearing / sound propagation
#include "xgenaimodule/C_SoundPropagationLayerBase.h"
#include "xgenaimodule/C_SoundPropagationLayerObstacles.h"
#include "xgenaimodule/C_SoundPropagationLayerNoisiness.h"
#include "xgenaimodule/C_SoundPropagationLayerWeather.h"
#include "xgenaimodule/C_SoundPropagationLayerAddIntensities.h"
#include "xgenaimodule/C_SoundPropagationLayerPlayerSurroundings.h"
#include "xgenaimodule/C_SoundPropagationLayerTargetRPG.h"
#include "xgenaimodule/C_SoundPropagationCircularQuery.h"
#include "xgenaimodule/C_HearingSystem.h"
// crime system
#include "xgenaimodule/I_CrimeDescription.h"
#include "xgenaimodule/S_VictimCrimeDescription.h"
#include "xgenaimodule/S_TheftDescription.h"
#include "xgenaimodule/S_AnimalCrimeDescription.h"
#include "xgenaimodule/S_VictimlessCrimeDescription.h"
#include "xgenaimodule/I_CrimeLevelAggregator.h"
#include "xgenaimodule/C_CrimeLevelAggregator.h"
#include "xgenaimodule/I_CrimeResolver.h"
#include "xgenaimodule/C_CrimeResolver.h"
#include "xgenaimodule/C_CrimeShelver.h"

// ---- Tranche 22: xgenaimodule wave G4A+G4B -- BRAIN family + variable system
//      (composed from analysis/xgenaimodule_port/G4A_dossier.md / G4B_dossier.md)
#include "xgenaimodule/Callbacks/C_NoDataExtensionBase.h"
#include "xgenaimodule/BehaviorTree/C_ExpressionRef.h"
#include "xgenaimodule/I_VariableIndex.h"
#include "xgenaimodule/C_VariableIndex.h"
#include "xgenaimodule/C_LocalVariableIndex.h"
#include "xgenaimodule/C_GlobalVariableIndex.h"
#include "xgenaimodule/C_OverwatchVariableIndex.h"
#include "xgenaimodule/C_Variable.h"
#include "xgenaimodule/C_SingleVariable.h"
#include "xgenaimodule/C_SingleVariableLuaReadOnly.h"
#include "xgenaimodule/C_IndexedArrayTreeVariable.h"
#include "xgenaimodule/C_AssociativeArrayTreeVariable.h"
#include "xgenaimodule/C_CustomAssociativeTreeVariable.h"
#include "xgenaimodule/I_StoredDecision.h"
#include "xgenaimodule/C_VariableDecision.h"
#include "xgenaimodule/S_ConstVariableReference.h"
#include "xgenaimodule/S_VariableReference.h"
#include "xgenaimodule/S_SilentVariableReference.h"
#include "xgenaimodule/I_Intellect.h"
#include "xgenaimodule/C_AIBrain.h"
#include "xgenaimodule/C_AIBrainSingleSubb.h"
#include "xgenaimodule/C_SubbSwitchingLogic.h"
#include "xgenaimodule/C_AIBrainMultiSubb.h"

// ---- Tranche 23: xgenaimodule wave G4C -- anim-event implementation strategies
//      (composed from analysis/xgenaimodule_port/G4C_dossier.md)
#include "xgenaimodule/I_AnimEventImplementation.h"
#include "xgenaimodule/C_TriggerPointEventImplementation.h"
#include "xgenaimodule/C_SpawnItemEventImplementation.h"
#include "xgenaimodule/C_SpawnedItemsCleanupEventImplemenation.h"
#include "xgenaimodule/C_AttachEventImplementation.h"
#include "xgenaimodule/C_DetachEventImplementation.h"
#include "xgenaimodule/C_DespawnItemEventImplementation.h"
#include "xgenaimodule/C_PickUpEventImplementation.h"
#include "xgenaimodule/C_PlaceEventImplementation.h"
#include "xgenaimodule/C_PhaseItemEventImplementationBase.h"
#include "xgenaimodule/C_SetItemPhaseEventImplementation.h"
#include "xgenaimodule/C_PhaseItemEventImplementation.h"
#include "xgenaimodule/C_MonologEventImplementation.h"
#include "xgenaimodule/C_MonologByAliasEventImplementation.h"
#include "xgenaimodule/C_MonologByMetaroleEventImplementation.h"

// ---- Tranche 24: xgenaimodule wave G5E -- SUBB (subbrain) fleet + host/listener
//      interface stubs (composed from analysis/xgenaimodule_port/G5E_dossier.md)
#include "xgenaimodule/I_NoRTTITypeInfo.h"
#include "xgenaimodule/I_CastableIface.h"
#include "xgenaimodule/I_BehaviorHost.h"
#include "xgenaimodule/I_SituationHolder.h"
#include "xgenaimodule/I_ResourceHost.h"
#include "xgenaimodule/I_SchedulerActivityHost.h"
#include "xgenaimodule/I_SmartEntitySubbrainListener.h"
#include "xgenaimodule/I_InjectionExternalDataUpdateListener.h"
#include "xgenaimodule/I_BehaviorToMonsterLODPostponer.h"
#include "xgenaimodule/I_SmartEntityListener.h"
#include "xgenaimodule/I_SmartAreaListener.h"
#include "xgenaimodule/C_SUBBBase.h"
#include "xgenaimodule/C_EmptySUBB.h"
#include "xgenaimodule/C_SmartEntitySubbrain.h"
#include "xgenaimodule/C_BehaviorTreeSUBB.h"
#include "xgenaimodule/C_SwitchingSubbrain.h"
#include "xgenaimodule/C_DialogSubbrain.h"
#include "xgenaimodule/C_DogCompanionSubbrain.h"
#include "xgenaimodule/C_SituationSubBrain.h"
#include "xgenaimodule/C_SmartObjectSubBrain.h"
#include "xgenaimodule/C_SmartAreaSubBrain.h"
#include "xgenaimodule/C_SchedulerSubbrain.h"

// ---- Tranche 24: xgenaimodule wave G5D -- situation subsystem (situations,
//      controller/manager, constraint searches, global conditions)
//      (composed from analysis/xgenaimodule_port/G5D_dossier.md)
#include "xgenaimodule/I_Situation.h"
#include "xgenaimodule/C_Situation.h"
#include "xgenaimodule/C_SituationController.h"
#include "xgenaimodule/I_SEBehaviorConditionManager.h"
#include "xgenaimodule/C_SituationManager.h"
#include "xgenaimodule/I_SchedulerInterruptListener.h"
#include "xgenaimodule/I_InjectionExternalDataProvider.h"
#include "xgenaimodule/C_SituationSubsystem.h"
#include "xgenaimodule/I_SituationSearch.h"
#include "xgenaimodule/C_AbstractSituationSearch.h"
#include "xgenaimodule/C_LazyNCSituationSearch.h"
#include "xgenaimodule/C_ForwardCheckingSituationSearch.h"
#include "xgenaimodule/I_SituationGlobalCondition.h"
#include "xgenaimodule/C_AbstractSituationGlobalCondition.h"
#include "xgenaimodule/C_AbstractPairwiseSituationGlobalCondition.h"
#include "xgenaimodule/C_DialogSituationGlobalCondition.h"
#include "xgenaimodule/C_BreakSymmetrySituationGlobalCondition.h"
#include "xgenaimodule/C_DistanceSituationGlobalCondition.h"
#include "xgenaimodule/C_PlayerDistanceSituationGlobalCondition.h"
#include "xgenaimodule/C_WeatherSituationGlobalCondition.h"

// ---- Tranche 25: xgenaimodule waves G6F+G6G+G6H -- smart entity family,
//      spatial operations/areas, LOD + remaining managers
//      (composed from analysis/xgenaimodule_port/G6{F,G,H}_dossier.md)
// shared templates / cross-module stubs
#include "framework/C_OverrideConflictManager.h"
#include "framework/C_PointManager.h"
#include "shared/C_TransformManager.h"
#include "entitymodule/I_InventoryManagerListener.h"
// G6F -- smart entity family
#include "xgenaimodule/I_SmartEntity.h"
#include "xgenaimodule/I_Area.h"
#include "xgenaimodule/I_PositionAndOrientation.h"
#include "xgenaimodule/I_SmartObjectsManager.h"
#include "xgenaimodule/I_SmartAreaManager.h"
#include "xgenaimodule/I_SmartObjectHelpersManager.h"
#include "xgenaimodule/I_SmartObjectsManagerListener.h"
#include "xgenaimodule/C_SmartEntity.h"
#include "xgenaimodule/C_InteractiveSmartEntity.h"
#include "xgenaimodule/C_SmartObject.h"
#include "xgenaimodule/C_SmartObjectDefault.h"
#include "xgenaimodule/C_NavigationSmartObject.h"
#include "xgenaimodule/C_SmartArea.h"
#include "xgenaimodule/C_SmartObjectsManager.h"
#include "xgenaimodule/C_SmartAreaManager.h"
#include "xgenaimodule/C_SmartObjectHelpersManager.h"
#include "xgenaimodule/C_SmartHelper.h"
#include "xgenaimodule/C_SmartBehaviorStateManager.h"
#include "xgenaimodule/C_SmartEntityResolver.h"
#include "xgenaimodule/I_SmartEnvironemntBehaviorCondition.h"
#include "xgenaimodule/C_AbstractSmartEnvironemntBehaviorCondition.h"
#include "xgenaimodule/C_SmartEnvironmentExpressionBehaviorCondition.h"
#include "xgenaimodule/C_SmartEnvironmentLuaBehaviorCondition.h"
#include "xgenaimodule/C_SmartEnvironmentDistanceToEntityBehaviorCondition.h"
#include "xgenaimodule/C_SmartEnvironmentSoulGenderBehaviorCondition.h"
#include "xgenaimodule/C_SmartEnvironmentDistanceToPlayerBehaviorCondition.h"
#include "xgenaimodule/C_SmartEnvironmentDistanceToPositioningAreaBehaviorCondition.h"
#include "xgenaimodule/C_SEEmptyElementCondition.h"
#include "xgenaimodule/C_SEAIBuffTagCondition.h"
// G6G -- spatial operations + areas
#include "xgenaimodule/I_SpatialOperation.h"
#include "xgenaimodule/C_PositionSpatialOperation.h"
#include "xgenaimodule/C_RotationSpatialOperation.h"
#include "xgenaimodule/C_TransformSpatialOperation.h"
#include "xgenaimodule/I_SpatialQueries.h"
#include "xgenaimodule/C_SpatialQueries.h"
#include "xgenaimodule/C_AreaProximityManager.h"
#include "xgenaimodule/C_TriggerArea.h"
#include "xgenaimodule/C_AreaUnion.h"
#include "xgenaimodule/C_AreaCallbackDispatch.h"
#include "xgenaimodule/E_AddRemove.h"
#include "xgenaimodule/C_AreaLabelManager.h"
#include "xgenaimodule/C_AreaLabelEffect.h"
// G6H -- LOD subsystem + remaining managers
#include "xgenaimodule/C_LODManager.h"
#include "xgenaimodule/C_LODAgent.h"
#include "xgenaimodule/I_LODHandle.h"
#include "xgenaimodule/I_PassiveUpdate.h"
#include "xgenaimodule/I_PositioningManager.h"
#include "xgenaimodule/C_PositioningManager.h"
#include "xgenaimodule/C_AIInventoryManager.h"
#include "xgenaimodule/I_NPCAttachListener.h"
#include "xgenaimodule/C_MountRiderLinkManager.h"
#include "xgenaimodule/C_LightSourceManager.h"
#include "xgenaimodule/C_ParticleEffectPuppetManager.h"
#include "xgenaimodule/C_IntelligentObjectManager.h"
#include "xgenaimodule/C_DogPointManager.h"
#include "xgenaimodule/C_AreaUnionManager.h"
#include "xgenaimodule/C_AITransformManager.h"
#include "xgenaimodule/I_IntermissionManager.h"
#include "xgenaimodule/C_IntermissionManager.h"
#include "xgenaimodule/I_AIKeyAccessManager.h"
#include "xgenaimodule/C_AIKeyAccessManager.h"
#include "xgenaimodule/I_LinkEditorValidator.h"
#include "xgenaimodule/C_LinkEditorValidator.h"

// ---- Tranche 26: xgenaimodule database family (Family A: template tree DBs;
//      Family B: hand-written mailbox/SE-condition DBs)
//      (composed from analysis/xgenaimodule_port/G6I_dossier.md)
#include "databasemodule/C_ObjectTreeDatabaseList.h"
#include "xgenaimodule/C_EnumDatabase.h"
#include "xgenaimodule/C_StructuredTypeDatabase.h"
#include "xgenaimodule/C_ScriptContextDatabase.h"
#include "xgenaimodule/C_TreeEventSetDatabase.h"
#include "xgenaimodule/C_TreeSignatureDatabase.h"
#include "xgenaimodule/C_DecisionLabelDatabase.h"
#include "xgenaimodule/C_StanceAnimDatabase.h"
#include "xgenaimodule/C_UnstanceDatabase.h"
#include "xgenaimodule/C_AIConceptSignalDatabase.h"
#include "xgenaimodule/C_DogPointDatabase.h"
#include "xgenaimodule/C_SmartObjectAnimationDatabase.h"
#include "xgenaimodule/I_SmartEntityDatabase.h"
#include "xgenaimodule/C_SmartEntityDatabase.h"
#include "xgenaimodule/C_MailboxDatabase.h"
#include "xgenaimodule/C_GlobalMailBoxDatabase.h"
#include "xgenaimodule/C_SEConditionDatabase.h"

// ---- Tranche 27: rpgmodule Cause family (I_Cause double-dispatch event causes;
//      93 concrete C_XxxCause + their S_XxxData payloads + C_Event wrapper +
//      I_RPGDialog scope for the nested SkillCheck payload)
//      (composed from analysis/rpgmodule_port/g11{a..e}_dossier.md; wf8i9sn4w)
#include "rpgmodule/I_RPGDialog.h"
#include "rpgmodule/E_EventState.h"
#include "rpgmodule/I_Event.h"
#include "rpgmodule/C_Event.h"
//   -- payload POD structs (no RTTI; size-proven) --
#include "rpgmodule/S_ActorLootData.h"
#include "rpgmodule/S_ActorLootDoneData.h"
#include "rpgmodule/S_AimBeginData.h"
#include "rpgmodule/S_AimEndData.h"
#include "rpgmodule/S_AlchemyFinishedData.h"
#include "rpgmodule/S_AlchemyRecipeFinishData.h"
#include "rpgmodule/S_AlchemyStartedData.h"
#include "rpgmodule/S_AthleticDistanceReachedData.h"
#include "rpgmodule/S_AttackData.h"
#include "rpgmodule/S_BarberServiceUsedData.h"
#include "rpgmodule/S_BlacksmithingFinishedData.h"
#include "rpgmodule/S_BlacksmithingLifetimeData.h"
#include "rpgmodule/S_BlacksmithingStartedData.h"
#include "rpgmodule/S_BlacksmithingStrokeData.h"
#include "rpgmodule/S_BlockingData.h"
#include "rpgmodule/S_BowDrawBeginData.h"
#include "rpgmodule/S_BowDrawEndData.h"
#include "rpgmodule/S_CaptionObjectUsedData.h"
#include "rpgmodule/S_ClothingWashedData.h"
#include "rpgmodule/S_CollisionHitData.h"
#include "rpgmodule/S_CombatDodgeData.h"
#include "rpgmodule/S_CombatHitData.h"
#include "rpgmodule/S_CompanionEventData.h"
#include "rpgmodule/S_CutsceneEndedData.h"
#include "rpgmodule/S_CutsceneStartedData.h"
#include "rpgmodule/S_DiceMinigameEndedData.h"
#include "rpgmodule/S_DiceMinigameStartedData.h"
#include "rpgmodule/S_DogFoundEventData.h"
#include "rpgmodule/S_DrunkennessData.h"
#include "rpgmodule/S_EncumberanceWalkDistanceReachedData.h"
#include "rpgmodule/S_FastTravelEndedData.h"
#include "rpgmodule/S_FastTravelStartedData.h"
#include "rpgmodule/S_ForgeAssetEnabledData.h"
#include "rpgmodule/S_GameOverData.h"
#include "rpgmodule/S_GenericActivateBuffData.h"
#include "rpgmodule/S_GenericAddBuffData.h"
#include "rpgmodule/S_GenericMinigameData.h"
#include "rpgmodule/S_GenericRemoveBuffsData.h"
#include "rpgmodule/S_HerbsCollectedData.h"
#include "rpgmodule/S_HorseIrritationActionData.h"
#include "rpgmodule/S_HorseOverspurrIrritationActionData.h"
#include "rpgmodule/S_HorseRidingDistanceReachedData.h"
#include "rpgmodule/S_InterruptedCarryCorpseData.h"
#include "rpgmodule/S_ItemDamagedOnConsciousnessLossData.h"
#include "rpgmodule/S_ItemEatData.h"
#include "rpgmodule/S_ItemRepairData.h"
#include "rpgmodule/S_ItemUseData.h"
#include "rpgmodule/S_JailEndedData.h"
#include "rpgmodule/S_KilledByTimerData.h"
#include "rpgmodule/S_LockpickingResultData.h"
#include "rpgmodule/S_LockpickingStartedData.h"
#include "rpgmodule/S_MissileHitData.h"
#include "rpgmodule/S_MovementActionData.h"
#include "rpgmodule/S_POIDiscoveredData.h"
#include "rpgmodule/S_PeriodicTimerData.h"
#include "rpgmodule/S_PickpocketingFinishedData.h"
#include "rpgmodule/S_PickpocketingStartedData.h"
#include "rpgmodule/S_PlayerCrimeLevelChangedData.h"
#include "rpgmodule/S_PlayerEndedToLootStashData.h"
#include "rpgmodule/S_PlayerIsActiveInCombatData.h"
#include "rpgmodule/S_PlayerIsInCombatDangerData.h"
#include "rpgmodule/S_PlayerIsWantedData.h"
#include "rpgmodule/S_PlayerOutfitChangedData.h"
#include "rpgmodule/S_PlayerOutfitSwitchedData.h"
#include "rpgmodule/S_PlayerStartedToLootStashData.h"
#include "rpgmodule/S_PotentialPlayerSneakingData.h"
#include "rpgmodule/S_PowerReadingFinishedData.h"
#include "rpgmodule/S_PowerReadingStartedData.h"
#include "rpgmodule/S_QuestObjectiveFinishedData.h"
#include "rpgmodule/S_QuestStateChangedData.h"
#include "rpgmodule/S_RandomEventData.h"
#include "rpgmodule/S_ReadingStartedData.h"
#include "rpgmodule/S_ReloadBeginData.h"
#include "rpgmodule/S_ReloadEndData.h"
#include "rpgmodule/S_RewardReceivedData.h"
#include "rpgmodule/S_ScriptedHitData.h"
#include "rpgmodule/S_SequenceEndedData.h"
#include "rpgmodule/S_SequenceStartedData.h"
#include "rpgmodule/S_SharpPedalingData.h"
#include "rpgmodule/S_SharpPressureData.h"
#include "rpgmodule/S_SharpeningFinishedData.h"
#include "rpgmodule/S_SharpeningStartedData.h"
#include "rpgmodule/S_SharpeningVictoryData.h"
#include "rpgmodule/S_ShoppingTransactionData.h"
#include "rpgmodule/S_SkillTeacherData.h"
#include "rpgmodule/S_SkipTimeEndedData.h"
#include "rpgmodule/S_SkipTimeStartedData.h"
#include "rpgmodule/S_SleepwalkingTeleportUsedData.h"
#include "rpgmodule/S_UIData.h"
#include "rpgmodule/S_UknownScriptData.h"
#include "rpgmodule/S_WeaponRaisedData.h"
//   -- concrete causes (thin C_Cause<T> subclasses; RTTI + size assert) --
#include "rpgmodule/C_ActorLootCause.h"
#include "rpgmodule/C_ActorLootDoneCause.h"
#include "rpgmodule/C_AimBeginCause.h"
#include "rpgmodule/C_AimEndCause.h"
#include "rpgmodule/C_AlchemyFinishedCause.h"
#include "rpgmodule/C_AlchemyRecipeFinishCause.h"
#include "rpgmodule/C_AlchemyStartedCause.h"
#include "rpgmodule/C_AthleticDistanceReachedCause.h"
#include "rpgmodule/C_AttackCause.h"
#include "rpgmodule/C_BarberServiceUsedCause.h"
#include "rpgmodule/C_BlacksmithingFinishedCause.h"
#include "rpgmodule/C_BlacksmithingLifetimeCause.h"
#include "rpgmodule/C_BlacksmithingStartedCause.h"
#include "rpgmodule/C_BlacksmithingStrokeCause.h"
#include "rpgmodule/C_BlockingCause.h"
#include "rpgmodule/C_BowDrawBeginCause.h"
#include "rpgmodule/C_BowDrawEndCause.h"
#include "rpgmodule/C_CaptionObjectUsedCause.h"
#include "rpgmodule/C_ClothingWashedCause.h"
#include "rpgmodule/C_CollisionHitCause.h"
#include "rpgmodule/C_CombatDodgeCause.h"
#include "rpgmodule/C_CombatHitCause.h"
#include "rpgmodule/C_CompanionEventCause.h"
#include "rpgmodule/C_CutsceneEndedCause.h"
#include "rpgmodule/C_CutsceneStartedCause.h"
#include "rpgmodule/C_DiceMinigameEndedCause.h"
#include "rpgmodule/C_DiceMinigameStartedCause.h"
#include "rpgmodule/C_DogFoundEventCause.h"
#include "rpgmodule/C_DrunkennessCause.h"
#include "rpgmodule/C_EncumberanceWalkDistanceReachedCause.h"
#include "rpgmodule/C_FastTravelEndedCause.h"
#include "rpgmodule/C_FastTravelStartedCause.h"
#include "rpgmodule/C_ForgeAssetEnabledCause.h"
#include "rpgmodule/C_GameOverCause.h"
#include "rpgmodule/C_GenericActivateBuffCause.h"
#include "rpgmodule/C_GenericAddBuffCause.h"
#include "rpgmodule/C_GenericMinigameCause.h"
#include "rpgmodule/C_GenericRemoveBuffsCause.h"
#include "rpgmodule/C_HerbsCollectedCause.h"
#include "rpgmodule/C_HorseIrritationActionCause.h"
#include "rpgmodule/C_HorseOverspurrIrritationActionCause.h"
#include "rpgmodule/C_HorseRidingDistanceReachedCause.h"
#include "rpgmodule/C_InterruptedCarryCorpseCause.h"
#include "rpgmodule/C_ItemDamagedOnConsciousnessLossCause.h"
#include "rpgmodule/C_ItemEatCause.h"
#include "rpgmodule/C_ItemRepairCause.h"
#include "rpgmodule/C_ItemUseCause.h"
#include "rpgmodule/C_JailEndedCause.h"
#include "rpgmodule/C_KilledByTimerCause.h"
#include "rpgmodule/C_LockpickingResultCause.h"
#include "rpgmodule/C_LockpickingStartedCause.h"
#include "rpgmodule/C_MissileHitCause.h"
#include "rpgmodule/C_MovementActionCause.h"
#include "rpgmodule/C_POIDiscoveredCause.h"
#include "rpgmodule/C_PeriodicTimerCause.h"
#include "rpgmodule/C_PickpocketingFinishedCause.h"
#include "rpgmodule/C_PickpocketingStartedCause.h"
#include "rpgmodule/C_PlayerCrimeLevelChangedCause.h"
#include "rpgmodule/C_PlayerEndedToLootStashCause.h"
#include "rpgmodule/C_PlayerIsActiveInCombatCause.h"
#include "rpgmodule/C_PlayerIsInCombatDangerCause.h"
#include "rpgmodule/C_PlayerIsWantedCause.h"
#include "rpgmodule/C_PlayerOutfitChangedCause.h"
#include "rpgmodule/C_PlayerOutfitSwitchedCause.h"
#include "rpgmodule/C_PlayerStartedToLootStashCause.h"
#include "rpgmodule/C_PotentialPlayerSneakingCause.h"
#include "rpgmodule/C_PowerReadingFinishedCause.h"
#include "rpgmodule/C_PowerReadingStartedCause.h"
#include "rpgmodule/C_QuestObjectiveFinishedCause.h"
#include "rpgmodule/C_QuestStateChangedCause.h"
#include "rpgmodule/C_RandomEventCause.h"
#include "rpgmodule/C_ReadingStartedCause.h"
#include "rpgmodule/C_ReloadBeginCause.h"
#include "rpgmodule/C_ReloadEndCause.h"
#include "rpgmodule/C_RewardReceivedCause.h"
#include "rpgmodule/C_ScriptedHitCause.h"
#include "rpgmodule/C_SequenceEndedCause.h"
#include "rpgmodule/C_SequenceStartedCause.h"
#include "rpgmodule/C_SharpPedalingCause.h"
#include "rpgmodule/C_SharpPressureCause.h"
#include "rpgmodule/C_SharpeningFinishedCause.h"
#include "rpgmodule/C_SharpeningStartedCause.h"
#include "rpgmodule/C_SharpeningVictoryCause.h"
#include "rpgmodule/C_ShoppingTransactionCause.h"
#include "rpgmodule/C_SkillCheckCause.h"
#include "rpgmodule/C_SkillTeacherCause.h"
#include "rpgmodule/C_SkipTimeEndedCause.h"
#include "rpgmodule/C_SkipTimeStartedCause.h"
#include "rpgmodule/C_SleepwalkingTeleportUsedCause.h"
#include "rpgmodule/C_UICause.h"
#include "rpgmodule/C_UknownScriptCause.h"
#include "rpgmodule/C_WeaponDestroyCause.h"
#include "rpgmodule/C_WeaponRaisedCause.h"

// ---- Tranche 28: damage-application pipeline (producers C_CombatSoul[42..45] ->
// S_DamageEventData -> dispatcher S_DamageEventData::Dispatch -> C_*ValueEffect deltas) ----
#include "rpgmodule/E_BloodZoneId.h"
#include "rpgmodule/E_DamageEventType.h"
#include "rpgmodule/E_DamageTypeMask.h"
#include "entitymodule/StabSlashSmashValue.h"
#include "rpgmodule/S_DealDamageParams.h"
#include "rpgmodule/S_DamageEventData.h"
